### ISSUE TITLE
Why auto resize ?

### ISSUE THREAD

**Issue by ghost** [dagrejs/dagre-d3#101]
This is my situation. 
The following code works as expected if the SVG tag is contained in the body. When the container is a modal (in my case I'm using a _bootstrap modal_), the nodes are resized (but not the text). This makes it impossible to adopt the zoom to fix the problem.

```
var renderer = new dagreD3.Renderer();
renderer.zoom(false);
renderer.edgeInterpolate('linear');

var svg = d3.select(parent),
    svgGroup = svg.select('g');

var layout = renderer.run(g, svgGroup);

var xCenterOffset = (svg.attr('width') - layout.graph().width) / 2;
svgGroup.attr('transform', 'translate(' + xCenterOffset + ', 20)');
svg.attr('height', layout.graph().height + 40);
```
### Expected (in _body_)

![a](https://cloud.githubusercontent.com/assets/1014793/4753848/fd206ece-5ab9-11e4-9360-586fc414f702.png)
### Unexpected (in _modal_)

![schermata del 2014-10-23 15 38 17](https://cloud.githubusercontent.com/assets/1014793/4753850/01c9eab8-5aba-11e4-854b-f0236d23c861.png)

I have already made several attempts to force the size of the height, which acts only on the size of the layout. **When it starts in modal, the height of layout is set to "0"**, so i forced it with a minimum heigth:

```
            var height = layout.graph().height;
            svg.attr('height', height>300?height:300 + 40);
```

Still in this case, the rendering is resized. Any indication?

**Comment by SarathVakacharla** [comment]
> In his case bootstrap was actually setting the svg to hidden during the rendering so the DOM gave values of 0 for dimensions.

I have the same problem. Is there is a workaround?



> We changed it to set opacity to 0 instead of setting display to hidden

what do you mean by this?
