### ISSUE TITLE
Clustering supported in 0.3.x?

### ISSUE THREAD

**Issue by ulilicht** [dagrejs/dagre-d3#110]
Hi, 

I have read somewhere that clustering is experimentally supported in v0.3 - unfortunately, I could'nt find any hint how to turn it own. 

Can you help me out? ;-) 

Thanks for your great work, 
uli

**Comment by iampeter** [comment]
ran into the same issue. 
why can't the cluster node have edges?

@ulilicht @niyue how have you handled?

**Comment by ulilicht** [comment]
@iampeter
I'm sorry I don't work with dagre any more as i'm on a different project now. Unfortunately I don't remember what the issue was ;-/  Good luck!

**Comment by snowystinger** [comment]
Has anyone managed to get this working? @ulilicht 's plunk doesn't work, gives the same error.
http://jsfiddle.net/snowystinger/fq0d7w5r/ (commented out the edges I want) I'm trying to do it with the plain version of Dagre, not sure if that makes a difference, both seem to give the same.

**Comment by jrgleason** [comment]
Would there be any downside to changing the Dagre project to allow a null check here...

    return (label.rank = rank);

**Comment by jrgleason** [comment]
Playing around it looks like that function is being constantly called. Does anyone know why graph.node(3) returns null for clusters?

**Comment by bitdivine** [comment]
Subgraphs work for me.  Here is a demo: http://bitdivine.github.io/dotfile-editor/dotfile-editor.html#http://bitdivine.github.io/dotfile-editor/sample.dot

**Comment by junneyang** [comment]
any solution?
thanks!
