### ISSUE TITLE
Highlight connected edges and nodes on clicking on a node

### ISSUE THREAD

**Issue by amitmishra684** [dagrejs/dagre-d3#114]
Hi, I am new to dagre-d3.js. Can any one suggest me how to highlight neighboring nodes and edges on clicking a node.

Thanks in advance.

**Comment by gaitat** [comment]
Did you figure this out? Do you have an example. Thank you.

**Comment by amitmishra684** [comment]
Yeah, I figured it out. Currently, I don't have the access to the code.
But, much as I remember you can follow these steps:
1.. Assign the id's of the nodes same as their labels.
2. There's an API in the dagre-d3 library which gives you all the children
of a given node and same for the parent as well. The API returns all the
children nodes as an array of labels.
    Hence, for each label treat it as an id and change the color attribute
of corresponding node element.

This was not of the simplest solutions. If you happen to find simpler one
please post in the thread.



On Tue, Jan 13, 2015 at 7:53 AM, gaitat <notifications@github.com> wrote:

> Did you figure this out? Do you have an example. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cpettitt/dagre-d3/issues/114#issuecomment-69685450>.
>



-- 
Cheers
Amit Mishra

**Comment by gaitat** [comment]
How do I change the color attribute of corresponding node element?

**Comment by amitmishra684** [comment]
Do "Inspect element" on a particular node. The default color of present
node is green. Figure out which html element has this property. Navigate to
that html element in the svg group and change its property to any desired
color.

On Thu, Jan 15, 2015 at 10:41 PM, gaitat <notifications@github.com> wrote:

> How do I change the color attribute of corresponding node element?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cpettitt/dagre-d3/issues/114#issuecomment-70121393>.
>



-- 
Cheers
Amit Mishra

**Comment by gaitat** [comment]
I had assumed there is a simple method. Thank you

**Comment by gaitat** [comment]
I have to re-render the graph in order for the style to take effect? That is very strange.

**Comment by amitmishra684** [comment]
You don't have to re-render. A simple "onclick" action will do.

On Fri, Jan 16, 2015 at 12:25 AM, gaitat <notifications@github.com> wrote:

> I have to re-render the graph in order for the style to take effect? That
> is very strange.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cpettitt/dagre-d3/issues/114#issuecomment-70140078>.
>



-- 
Cheers
Amit Mishra
