### ISSUE TITLE
How to make the edge as smooth line

### ISSUE THREAD

**Issue by bubkoo** [dagrejs/dagre-d3#115]
Demos: 
- http://cpettitt.github.io/project/dagre-d3/latest/demo/hover.html
- http://cs.brown.edu/people/jcmace/d3/graph.html?id=small.json

The second one's edge is smooth. So, how to get smooth lines?

**Comment by gaitat** [comment]
Where do we find all graph options, all node options and all edge options?
Is there documentation?

Thank you.
