### ISSUE TITLE
dagreD3.layout(): Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by beberlei** [dagrejs/dagre-d3#117]
When calling dagreD3.layout() i get the following error:

Uncaught TypeError: undefined is not a function.

This is with the dagre-d3.js from the `dist/` folder in version 3.*

**Comment by Lily-Jian** [comment]
//My code is as follows:
` var layout = dagreD3.layout()
                    .rankDir("LR");
    render.layout(layout).run(g, d3.select("svg g"));`
The system prompt error is as follows:TypeError: dagreD3.layout is not a function.
please help me!
