### ISSUE TITLE
Github uses https; demos source D3 over HTTP

### ISSUE THREAD

**Issue by shevek** [dagrejs/dagre-d3#126]
Demos fail in firefox: https://developer.mozilla.org/en-US/docs/Security/MixedContent because github wiki and pages use https, but demos source d3 over http.

**Comment by sknebel** [comment]
@cpettitt Would you accept a pull request making these changes?

I was hit by this today since I use the "HTTPS anywhere" browser extension, which redirects all sites hosted by github to HTTPS. All such users are seeing completely broken demo pages

**Comment by cpettitt** [comment]
I'll take a pull request for this.

**Comment by cpettitt** [comment]
Should be fixed
