### ISSUE TITLE
dagre-D3 demo examples are not working in IE

### ISSUE THREAD

**Issue by valasa** [dagrejs/dagre-d3#128]
I have downloaded the dagre-D3-v0.3.2. Demo examples are working fine in Firefox and chrome, but when I opened in IE( all IE versions) it is not working, in the console I saw below message

SCRIPT5022: NoModificationAllowedError
File: dagre-d3.js, Line: 272, Column: 5

Note: I changed the folder "lib" to "build" as in the demo html files are referring to build directory.

**Comment by itscharu** [comment]
I can still see issue with the latest demo - http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html. I am using IE 11

**Comment by kenseehart** [comment]
Ditto. Seems that it is completely broken on IE. That's a deal breaker unfortunately. Sure, I prefer Chrome myself, but I can't require that of my customers.
