### ISSUE TITLE
`gulp dist` does not copy the files from build to dist Win10

### ISSUE THREAD

**Issue by jrgleason** [dagrejs/dagre-d3#213]
I am on Win10 and if I edit the Karma confs to pull from build everything works great but the normal `gulp dist` never copies the files back to `./dist`.

**Comment by cpettitt** [comment]
Karma should have been pulling from `build/dist` and not `dist`. There was a chicken and egg problem where karma was testing on the `dist` files and the build script would only copy `build/dist` to `dist` if this succeeded.

I'm checking in a fix to use `build/dist` shortly. Let me know if that does not fix the copying issue you've described above. I don't have a windows box to test on, unfortunately.

**Comment by cpettitt** [comment]
Closing as this appears to be resolved.
