### ISSUE TITLE
Dagre uses only global d3 instead of adaptive (CommonJS or global)

### ISSUE THREAD

**Issue by ynosa** [dagrejs/dagre-d3#220]
I get "unknown" error  for d3 variable in create-edge-lables.js
In d3.js

```
module.exports = window.d3;
```

Seems it doesn't try load d3 via CommonJS, only global

D3 should have same adaptive dependency as say lodash.js in lib

```
var lodash;
if (require) {
  try {
    lodash = require("lodash");
  } catch (e) {}
}

if (!lodash) {
  lodash = window._;
}

module.exports = lodash;

```

**Comment by michaelkariv** [comment]
Same problem. Trying to make it run on nodejs.
