### ISSUE TITLE
Update to lodash 4

### ISSUE THREAD

**Issue by Kepro** [dagrejs/dagre-d3#253]
why are you still using old lodash?

**Comment by chriswebb** [comment]
Hey man, just a heads up, on their README they say:

> This project is not being actively developed or maintained.

**Comment by cpettitt** [comment]
We need to do this before we pull in the latest dagre as we've moved dagre to lodash 4.

**Comment by khitrenovich** [comment]
I see relevant changes came in recently via https://github.com/dagrejs/dagre-d3/pull/301. Do you plan to release it soon?

**Comment by cpettitt** [comment]
Published in v0.6.0
