### ISSUE TITLE
Zoom feature

### ISSUE THREAD

**Issue by tduchateau** [dagrejs/dagre-d3#27]
Hi,

Thanks a lot for your project. This is quite impressive!
I was wondering if there's any way to add some zooming feature (allowing to zoom in/out inside the svg).

Thanks!
Regards,
Thibault

**Comment by graphdude** [comment]
hi,
can someone give me an idea how to add navigation buttons in dagre graphusing d3 verwsion 4?
Should I use translate?
Thanks in advance.
