### ISSUE TITLE
Anyway to remove the existing edge?

### ISSUE THREAD

**Issue by pradeepb6** [dagrejs/dagre-d3#284]
Please look at the example [here](https://jsfiddle.net/s95npdkt/)

After the graph is drawn,  I am trying to remove an edge by below code. I am not sure if its correct.

`g.removeEdge('CLOSED', 'LISTEN','open');`

Any help would be appreciated. Thanks.

**Comment by alanhg** [comment]
My current method is destroying exist graph and redraw.

**Comment by TomasHubelbauer** [comment]
https://github.com/dagrejs/graphlib/wiki/API-Reference#removeEdge

There seems to be a method for this now.
