### ISSUE TITLE
curved edges/paths

### ISSUE THREAD

**Issue by tzookb** [dagrejs/dagre-d3#305]
Tried to go over the docs and google but could not find nothing :/

the only thing similar is this:

```
graph.setEdge("D", "Z", {
    label: "A to zppppp",
    labelStyle: "font-style: italic; text-decoration: underline;",
    lineInterpolate: 'basis'
  });
```

but it didnt curved my edge, any ideas?

thanks!

**Comment by sunlisha** [comment]
v4 of dagre-d3 got an update: https://github.com/dagrejs/dagre-d3/pull/267/commits/980ea8c435a5043708e18017950523698592d7f8

instead of lineInterpolate: 'basis' use lineCurve: d3.curveBasis

This took me a while to figure out also.

**Comment by lutzroeder** [comment]
dagre-d3 is now using D3.js v4 and new D3.js v4 approach for curves  @sunlisha described above.

**Comment by lutzroeder** [comment]
In dagre-d3 v0.6.1 this will change to `curve: d3.curveBasis` and samples will be updated to use the new approach.

**Comment by tzookb** [comment]
worked like a charm!

thanks guys!!

**Comment by tzookb** [comment]
Hey guys

another question you probably know.

I love the above solution for the arrow, but if I want a different curved style arrow like this image:

any idea how I can achieve that?

Thanks in advance!!

![aaa](https://user-images.githubusercontent.com/3749973/35742414-0bc6ce5c-0843-11e8-8afc-dd23f705a424.jpg)

**Comment by cpettitt** [comment]
It looks like what you want is orthogonal routing of the edge, which is not something currently supported by dagre.

**Comment by tzookb** [comment]
Thanks @cpettitt 

I noticed I can pass in a function to the `lineCurve`
and I see the path, but can't wrap my head around of what to do with it.

like this:
```
{
    lineCurve: context => {
        console.log(context);
        return new d3.curveBasis(context);
    }
}
```

```
Path:
_: "M518.6015625,120.0625L518.6015625,120.0625C518.6015625,120.0625,518.6015625,120.0625,518.6015625,120.0625C518.6015625,120.0625,518.6015625,120.0625,518.6015625,120.0625L518.6015625,120.0625",
_x0: 518.6015625,
_x1: 518.6015625,
_y0: 120.0625,
_y1: 120.0625
```

**Comment by cpettitt** [comment]
The x, y coordinates are control points - points where the edge must pass
through per the layout assignment. As those are prefixed with an underscore
I think that is internal data (either from dagre or d3). Take a look at
https://github.com/dagrejs/dagre/wiki#an-example-layout, which describes
the public way to get the control points.

**Comment by tzookb** [comment]
Thanks @cpettitt 

it looks great, but I want to keep using Dagre-D3

and it seems like I can pass the `lineCurve`

I could probably go find the points and connect them by myself, but surely there is a better way :/

**Comment by sateesh2499** [comment]
@tzookb did you find any way to create custom curves?

**Comment by tzookb** [comment]
Sorry @sateesh2499

I moved from Dagre 
I'm outputting a tree with d3 graph

**Comment by sateesh2499** [comment]
Okay. Thanks @tzookb

**Comment by gnganpath** [comment]
It's working at Angular 7 component mapping also. g.setEdge(sourceEdge, targetEdge, { curve: d3.curveBasis });

**Comment by herzaso** [comment]
It's a bit old but for future reference, here's how I handled it:

Create a curve function:
```
const BezierCurve = (context) => ({
  lineStart() {
    this.data = [];
  },

  point(x, y) {
    this.data.push([x, y]);
  },

  lineEnd() {
    const [x0, y0] = this.data[0];
    const [cp1x, cp1y] = this.data[1];
    const [cp2x, cp2y] = this.data[this.data.length - 2];
    const [x1, y1] = this.data[this.data.length - 1];
    context.moveTo(x0, y0);
    context.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x1, y1);
  },
});
```

Assign the curve function to the edges:
```
g.setEdge(from, to, { curve: BezierCurve });
```

**Comment by hijoncon** [comment]
@herzaso any tip for arcTo?
