### ISSUE TITLE
TypeError: svgEdgeLabels.exit is not a function at function createEdgeLabels

### ISSUE THREAD

**Issue by AlbertoCastelo** [dagrejs/dagre-d3#309]
This function was previously working correctly. Now it throws this error when I'm trying to render my graph

**Comment by feelfine1977** [comment]
I have the same problem. It seems to work with d3v4. The problem occurs in d3.v3.5.5. When I use d3v4.13 it works.

**Comment by feelfine1977** [comment]
So I checked it and the last version of dagre-d3 that works with d3v3 without that error is dagre-d3v0.4.18. Dagre from the version v.0.5. and up throws the error.

**Comment by seelmann** [comment]
Tested with v0.6.3 which includes #313, but then I get a different error (using d3 v3.5.15):

```
Uncaught TypeError: previousPaths.merge is not a function
    at createEdgePaths (dagre-d3.min.js:26)
    at Array.fn (dagre-d3.min.js:93)
    at Array.Co.call (d3.min.js:3)
    at graph?dag_id=demo:1131
```
