### ISSUE TITLE
How do I decrease width of graph?

### ISSUE THREAD

**Issue by tobiasdr** [dagrejs/dagre-d3#338]
I have graph with around 100 nodes and 200 edges and the graph becomes extremely wide. I would like to have all nodes on the page. I have tried adjusting parameters such as edgesep and nodesep but it didnt improve. Would appreciate any help, thank you!

<img width="932" alt="bildschirmfoto 2018-08-30 um 09 32 04" src="https://user-images.githubusercontent.com/32938372/44839911-d3b78a80-ac37-11e8-9e4a-12b8404793e2.png">

**Comment by ceerqingting** [comment]
have you fixed that problem?

**Comment by larissa-n** [comment]
Was this ever solved?
