### ISSUE TITLE
Clustering nodes in groups and horizontal placement

### ISSUE THREAD

**Issue by sajoku** [dagrejs/dagre-d3#345]
I'm trying to create a network type graph using the clustering demo.
There are groups (LAN) and they can have multiple nodes (Servers).
The graph I'm now generating get's really wide as all nodes are placed horizontally. I want to tell the graph to place not more than 5 nodes next to each other. Is there some way of doing this? 
I tried altering `order:` and `rank:` but that does not seem to do anything.

This is how it currently look. 
<img width="785" alt="vlan with nodes" src="https://user-images.githubusercontent.com/390331/49233535-81346880-f3f6-11e8-84c7-0ade91251637.png">

Anyone that can point me in the right direction?

**Comment by sajoku** [comment]
Closing this since there does not seem to be anybody having the same issue or there's not an, easy, solution.

**Comment by larissa-n** [comment]
Was this ever solved?

**Comment by sajoku** [comment]
Nope it wasn't @larissa-n .
I eventually went with a different library named [visjs](https://visjs.org)
