### ISSUE TITLE
Set node text color

### ISSUE THREAD

**Issue by Anton-4** [dagrejs/dagre-d3#346]
First of all, thank you for this useful open source project!
I have a very simple question: how do I change the color of text inside a node?

My css is ignored somehow even though firefox inspector shows that it is applied.
![image](https://user-images.githubusercontent.com/17049058/49794509-09d8d000-fd38-11e8-9cd4-f6af4e0111de.png)

**Comment by git-ashish** [comment]
@Anton-4 CSS property color doesn't work with text elements. Use fill or stroke based on youre requirement. See [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Fills_and_Strokes).

**Comment by Anton-4** [comment]
Ah yes obviously, thanks for the quick response!
