### ISSUE TITLE
Multigraph has something wrong when change style

### ISSUE THREAD

**Issue by MeiRuiSu** [dagrejs/dagre-d3#354]
When use multigraph, I got something strange, seems render has something wrong. 
<img width="308" alt="screen shot 2019-01-14 at 2 36 53 pm" src="https://user-images.githubusercontent.com/42774956/51099126-ece95e00-1809-11e9-8717-b3ba4d475fae.png">
If only one edge between node "Kevin Spacey" and "Saul Williams",  everything is fine. If no style in the setEdge and it's fine also.  Can you help me on how to remove the black triangle background?
Code is here:
let g = new dagreD3.graphlib.Graph({ multigraph: true });
g.setGraph({});
g.setDefaultEdgeLabel(function() {
      return {};
});
g.setNode('kspacey', { label: 'Kevin Spacey' });
g.setNode('swilliams', { label: 'Saul Williams' });
g.setNode('bpitt', { label: 'Brad Pitt' });
g.setNode('hford', { label: 'Harrison Ford' });
g.setNode('lwilson', { label: 'Luke Wilson' });
g.setNode('kbacon', { label: 'Kevin Bacon' });

// Add edges to the graph.
g.setEdge('kspacey', 'swilliams', {style: 'stroke: #FF4A4E', label: 'kspacey-swilliams'}, 'kspacey-swilliams');
g.setEdge('kspacey', 'swilliams', {label: 'kspacey-swilliams-2'}, 'kspacey-swilliams-2');
g.setEdge('swilliams', 'kbacon');
g.setEdge('bpitt', 'kbacon');
g.setEdge('hford', 'lwilson');
g.setEdge('lwilson', 'kbacon');
render(inner, g);

**Comment by MeiRuiSu** [comment]
Resolved by change
 .edgePath path {
  stroke: #333;
  fill: #fff;
  stroke-width: 1.5px;
}

**Comment by gkrishnan724** [comment]
Hi,
I am having the same problem.

The solution you suggested also keeps the arrow-heads as white, which I don't want.

Is there any workaround this?

**Comment by mcdemarco** [comment]
> Hi,
> I am having the same problem.
> 
> The solution you suggested also keeps the arrow-heads as white, which I don't want.
> 
> Is there any workaround this?

```
.edgePath path.path {
	stroke: #333;
	fill: #fff;
	stroke-width: 1.5px;
}
```
