### ISSUE TITLE
Controlling nodes positions

### ISSUE THREAD

**Issue by pmario26** [dagrejs/dagre-d3#356]
Hi, i'm working on a project with dagre-d3 and would like to know if in the current lib version is there any way i can control the position of some nodes, to keep then not only together (like clustering do) but also mostly alligned together.
For example,in the picture below the selected nodes are grouped together inside the cluster, but they are still scattered.
![graph_before](https://user-images.githubusercontent.com/18668861/53020364-832a2880-3435-11e9-924f-46c425e71aa3.png)

What i would like to do is to draw these nodes in a single line, alligned together instead of scattered,like this:
![graph](https://user-images.githubusercontent.com/18668861/53019868-807b0380-3434-11e9-8339-8784bd4847f6.png)

Is there anyway i can achieve that with the current version of the lib ?
If not, how could i go about changing the lib to achieve that ?

**Comment by pmario26** [comment]
I have reseached past issues and found some old threads that are related to my issue.
https://github.com/dagrejs/dagre/issues/201
https://github.com/dagrejs/dagre-d3/issues/64
Are these fixes still possible in the current version of dagre ?
I think that being able to control the ranks of nodes would also help, but this feature appears to have been deprecated.

**Comment by mmazanec22** [comment]
@pmario26 did you end up figuring this out?  I'm in a similar situation-- need to stagger nodes at same level into separate rows so the text inside is readable on mobile
