### ISSUE TITLE
Mouse event support

### ISSUE THREAD

**Issue by bsr203** [dagrejs/dagre-d3#67]
Hello,

Is it possible to set mouse events to the nodes and links ? In normal d3, I use `.on` 

https://github.com/mbostock/d3/wiki/Selections#on

I could think of selecting the elements through d3, and then add this attribute. But was thinking more like a function callback which sets the correct event handler (or even other attributes like style,..). Or is a better way.

thanks for this project.
bsr.

**Comment by jeltedeproft** [comment]
this code gives me a syntax error, has it changed in the meantime?
