### ISSUE TITLE
position of not connected nodes

### ISSUE THREAD

**Issue by normanyahq** [dagrejs/dagre-d3#77]
I've used this lib to render the graph with hundreds of nodes, which shows the connection of data flow network.

However, in my case, there are many nodes that have no edge in or out. In current layout algorithm, they are placed in the top level, which makes the graph extremely wide but with only two or three levels, and the nodes with edges are scattered in a wide range.

I haven't read through the three papers mentioned in the wikipage of dagre project though, but there must be a solution for this.

I'm now trying to figure out a hackish solution: add some fake-edges to those nodes, so that they can be rendered in several layers, and then make them invisible with css style configuration.

**Comment by assafsun** [comment]
Hi,

Any update if there is an option for solving this point since it was opened?

Thanks!
