### ISSUE TITLE
Problem with label positions (center)

### ISSUE THREAD

**Issue by jk171505** [dagrejs/dagre-d3#83]
I'm able to properly position labels like this: 

```
                _svg.selectAll('.edgePath').each(function () {

                    var _correspondingLabel = _svg.select('.edgeLabels .' + d3.select(this).attr('data-link-id')),
                        _clY = d3.transform(_correspondingLabel.attr('transform')).translate[1],
                        _edgePath = d3.select(this).select('path');

                    for (var i = 0; i < _edgePath.node().getTotalLength(); i++) {

                        if (_edgePath.node().getPointAtLength(i).y >= _clY) {

                            _correspondingLabel.attr('transform', function () {
                                return 'translate(' + _edgePath.node().getPointAtLength(i).x + ',' + d3.transform(d3.select(this).attr('transform')).translate[1] + ')';
                            });
                            break;
                        }
                    }

                });
```

unfortunately Firefox hangs when getPointAtLength() is called (bug reported in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1044355).

So, the question is: is there any other way to properly adjust the position of labels?

example of the problem:
http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html?graph=%2F*%20Example%20*%2F%0Adigraph%20%7B%0A%20%20%20%20%2F*%20Note%3A%20HTML%20labels%20do%20not%20work%20in%20IE%2C%20which%20lacks%20support%20for%20%3CforeignObject%3E%20tags.%20*%2F%0A%20%20%20%20A%20%5Blabel%3D%22%3Cdiv%20style%3D%27padding%3A%2010px%3B%27%3EA%20%3Cspan%20style%3D%27font-size%3A32px%27%3EBig%3C%2Fspan%3E%20%3Cspan%20style%3D%27color%3Ared%3B%27%3EHTML%3C%2Fspan%3E%20Source!%3C%2Fdiv%3E%22%5D%3B%0A%20%20%20%20C%3B%0A%20%20%20%20E%20%5Blabel%3D%22Bold%20Red%20Sink%22%2C%20style%3D%22fill%3A%20%23f77%22%20labelStyle%3D%22font-weight%3A%20bold%22%5D%3B%0A%20%20%20%20A%20-%3E%20B%20-%3E%20C%3B%0A%20%20%20%20B%20-%3E%20D%20%5Blabel%3D%22A%20blue%20label%22%20labelStyle%3D%22fill%3A%20%2355f%3B%20font-weight%3A%20bold%3B%22%5D%3B%0A%20%20%20%20D%20-%3E%20E%20%5Blabel%3D%22A%20thick%20red%20edge%22%20style%3D%22stroke-width%3A%203px%3B%20stroke%3A%20%23f77%3B%22%5D%3B%0A%20%20%20%20C%20-%3E%20E%3B%0A%20%20%20%20A%20-%3E%20D%20%5Blabel%3D%22test22%22%5D%3B%0AA-%3EF%20%5Blabel%3D%22test2%22%5D%3B%0AA-%3Eg%20%5Blabel%3D%22test%22%5D%3B%0AA-%3EH%20%5Blabel%3D%22test3%22%5D%3B%0AA-%3EI%5Blabel%3D%22test4%22%5D%3B%0A%7D%0A%20%20

**Comment by surfjedi** [comment]
Any one still workingon this?
